
// TODO: make automatic

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VERSION_TWEAK 20190523
#define VERSION_EXTRA ""


#define STRING2(x) #x
#define STRING(x) STRING2(x)

#define VERSION_STRING STRING(VERSION_MAJOR) STRING(.) STRING(VERSION_MINOR) STRING(.) STRING(VERSION_PATCH) STRING(.) STRING(VERSION_TWEAK)
