
// TODO: make automatic

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VERSION_TWEAK 20180806
#define VERSION_EXTRA ""
#define VERSION_STRING "VERSION_MAJOR##.##VERSION_MINOR##.##VERSION_PATCH##.##VERSION_TWEAK"
